[versions]
detekt = "1.19.0"  # Note: Plugin versions must be updated in the settings.gradle.kts too
kotlin = "1.7.20"

groovy = "3.0.8"
jansi = "2.4.0"
kord-extensions = "1.5.5-20220925.092000-32"
kx-ser = "1.3.2"
logging = "3.0.0"
logback = "1.4.1"
jankson = "1.2.1"

[libraries]
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }
kx-ser = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kx-ser" }
jankson = { module = "blue.endless:jankson", version.ref = "jankson"}